
#    path:     /hello/{name}
#    defaults: { _controller: PolcodeCasperBundle:Default:index }

casper_index:
        path:   /
        defaults: { _controller: PolcodeCasperBundle:Default:index }

casper_test:
        path:   /test/{name}
        defaults: 
            _controller: PolcodeCasperBundle:Default:test
            name: asdf
