
#    path:     /hello/{name}
#    defaults: { _controller: PolcodeCasperBundle:Default:index }

casper_index:
        path:   /
        defaults: { _controller: PolcodeCasperBundle:Default:index }

casper_test:
        path:   /test/{name}
        defaults: 
            _controller: PolcodeCasperBundle:Default:test
            name: asdf

casper_newEvent:
        path:   /event/new
        defaults: 
            _controller: PolcodeCasperBundle:Event:newEvent

casper_ajaxCall:
        path:   /ajax
        defaults: 
            _controller: PolcodeCasperBundle:Default:ajaxCall

casper_userMyEvents:
        path:   /user/my-events
        defaults: 
            _controller: PolcodeCasperBundle:User:myEvents