services:
    casper_user.registration.form.type:
        class: Polcode\CasperBundle\Forms\RegistrationFormType
        tags:
            - { name: form.type, alias: casper_user_registration }
#    polcode_casper.example:
#        class: Polcode\CasperBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
