<?php

namespace Polcode\CasperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {
    
    public function findTheClosest($latitude, $longitude, $distance) {
        $latitude = (double)$latitude;
        $longitude = (double)$longitude;
        $distance = (double)$distance;
        
        $queryBuilder = $this->getEntityManager()->getConnection()->createQueryBuilder();
        $queryBuilder
                ->select('id', 'private', 'eventname', 'description', 'eventstart', 'eventstop', 'maxguests', 'eventsignupenddate', 'location', '(6371 * acos( cos( radians( :latitude ) ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians( :longitude ) ) + sin( radians( :latitude ) ) * sin( radians( latitude ) ) )) AS distance')
                ->from('events', 'e')
                ->having('distance < :distance')
                ->setParameters(array(
                    'longitude' => $longitude,
                    'latitude' => $latitude,
                    'distance' => $distance
                ));
        
        $events = $queryBuilder->execute()->fetchAll();
        
        return $events;
    }
}