<?php

namespace Polcode\CasperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {
    
    public function findTheClosest($params) {
        
        $queryBuilder = $this->getEntityManager()->getConnection()->createQueryBuilder();
        $queryBuilder
                ->select('id', 'user', 'private', 'eventname', 'description', 'eventstart', 'eventstop', 'maxguests', 'eventsignupenddate', 'latitude','longitude','location', 
                        '(6371 * acos(cos(radians( :latitude )) * cos(radians(latitude)) * cos(radians(longitude) - radians( :longitude )) + sin(radians( :latitude )) * sin(radians(latitude)))) as distance')
                ->from('events', 'e')
                ->having('distance <= :distance')
                ->setParameters($params);
        
        $events = $queryBuilder->execute()->fetchAll();
        
        return $events;
    }
}