# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: "@PolcodeCasperBundle/Resources/config/services.yml" }

parameters:
#    parameter_name: value

services:
    my_user_provider:
        class: Polcode\CasperBundle\Security\Core\User\FOSUBUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebook_id}]
        
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider